routes:
  /api/v1:
    /auth:
      /login:
        POST: Auth.Login
    
    /groups:
      /:
        GET: Groups.All
      /:slug:
        GET: Groups.GetBySlug
      /:group/clients/:client:
        GET: Clients.GetBySlug
    
    /clients:
      /:
        GET: Clients.All
