routes:
  /api/v1:
    /groups:
      /:
        GET: Groups.All
      /:slug:
        GET: Groups.GetBySlug
    
    /clients:
      /:
        GET: Clients.All
      /:slug:
        GET: Clients.GetBySlug
