routes:
  /api/v1:
    /groups:
      /:
        GET: Groups.All
      /:slug:
        GET: Groups.GetBySlug
      /:group/clients/:client:
        GET: Clients.GetBySlug
    
    /clients:
      /:
        GET: Clients.All
